---
repos:
  # Apply a selection of the pre-commit built-in validators
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      # Prevent giant files from being committed
      - id: check-added-large-files
      # Forbid files which have a UTF-8 byte-order marker
      - id: check-byte-order-marker
      # Checks that non-binary executables have a proper shebang
      - id: check-executables-have-shebangs
      # Attempts to load all json files to verify syntax
      - id: check-json
      # Attempts to load all yaml files to verify syntax
      - id: check-yaml
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Attempts to load all yaml files to verify syntax
      - id: check-yaml
        args:
          - --allow-multiple-documents
      # Check for debugger imports and py37+ breakpoint() calls in python source
      - id: debug-statements
      # Checks for the existence of private keys
      - id: detect-private-key
      # Makes sure files end in a newline and only a newline
      - id: end-of-file-fixer
      # Replaces or checks mixed line ending
      - id: mixed-line-ending
        args:
          - --fix=auto
      # Checks that all your JSON files are pretty
      - id: pretty-format-json
        args:
          - --autofix
      # Trims trailing whitespace
      - id: trailing-whitespace


  - repo: https://github.com/asottile/add-trailing-comma
    rev: v1.3.0
    hooks:
      # Automatically add trailing commas to calls and literals.
      - id: add-trailing-comma

  - repo: local
    hooks:
      - id: black
        name: Check Syntax
        language: system
        entry: make check.syntax

  - repo: local
    hooks:
      - id: pylint
        name: Check Lint
        language: system
        entry: make check.lint

  - repo: local
    hooks:
      - id: mypy
        name: Check Types
        language: system
        entry: make check.type

  - repo: local
    hooks:
      - id: isort
        name: Check Imports
        language: system
        entry: make check.imports

  - repo: local
    hooks:
      - id: pydocstyle
        name: Check Documentation
        language: system
        entry: make check.doc

  - repo: local
    hooks:
      - id: requirements
        name: Check Requirements
        language: system
        entry: make check.requirements

  - repo: local
    hooks:
      - id: bandit
        name: Check Security
        language: system
        entry: make check.security

  - repo: meta
    hooks:
      # Ensure each hook is used
      # - id: check-hooks-apply
      # Make sure there are no unnecessary excludes in the above checks
      - id: check-useless-excludes
